comindware/core-ui

- js/core/form/editors/impl/dateTime/views/DatePanelView.js
- js/core/form/editors/impl/dateTime/views/TimeView.js
Editor now sets & displays date/time in local time zone, but stores in UTC
> #304522 DateTimeEditor fix

- src/form/editors/DateTimeEditorView.js
> [date/time] update button title after clear button, forbid open dropdown if not access

- resources/styles/dropdown.css
- src/form/editors/MultiSelectEditorView.js
- src/form/editors/impl/multiSelect/templates/multiSelectItem.hbs
- src/form/editors/impl/multiSelect/templates/multiSelectPanel.hbs
- src/form/editors/impl/multiSelect/views/MultiSelectPanelView.js
> [#38772] fix multiSelect Editor

- demo/public/app/cases/components/PopupView.js
- resources/styles/themes/main/index.js
- resources/styles/themes/main/styles.css
- resources/styles/themes/new/index.js
- resources/styles/themes/new/styles.css
- resources/styles/themes/theme.css
- src/layout/popup/PopupView.js
- src/layout/popup/popup.hbs
- src/layout/resources/popup.css
- src/utils/handlebars/getIconPrefixer.js
> Popup: add ability to drag out the screen, to expand, add (open in new tab) button

- resources/styles/themes/main/index.js
- resources/styles/themes/new/index.js
- resources/styles/themes/new/styles.css
- resources/styles/themes/theme.css
- src/Meta.js
- src/layout/button/ButtonView.js
- src/layout/button/button.hbs
- src/layout/popup/PopupView.js
- src/layout/popup/popup.hbs
- src/services/MessageService.js
> Popup: add pale style to cancel button. Button: add ability to pale style. Some layout fixes, add IconsNames to Meta

- src/form/editors/DateTimeEditorView.js
- src/form/editors/iconsWraps/iconWrapTime.html
> TimeEditor: fix empty icon. (calendar to watch)

- src/dropdown/views/DropdownView.js
> Dropdown: if dropdown bigger button dropdown displace left.

- demo/public/app/cases/components/Form.js
- src/form/editors/DatalistEditorView.js
- tests/specs/form/DatalistEditorView.spec.js
small updates:
- add ability fetchUpdateFilter with dont opent panel.
- enhancment onFocus, onBlur.
> Datalist: onBlur clean input, fix open after set if maxQu = 1. add tests. small updates.

- src/form/editors/DatalistEditorView.js
- tests/specs/form/DatalistEditorView.spec.js
another:
- add some ToDo.
- small enchancment open function.
- small other enchancment.
> Datalist: fix fetch data on outer delete bubble (selected) delete.

- package.json
- src/form/editors/DatalistEditorView.js
- tests/specs/form/DatalistEditorView.spec.js
Show model value regardless panelCollection.
Show text from panelCollection on render through fetch, therefore fetch on render. (!!!)
> Datalist: show text from panelCollection on render through fetch.

- demo/public/demoPage/views/CanvasView.js
- src/form/editors/impl/iconEditor/categories.json
- src/form/editors/impl/iconEditor/icons.json
> Icons: update meta to 5.5.0.

- src/form/editors/DatalistEditorView.js
- tests/specs/form/DatalistEditorView.spec.js
… panel, -select all value items, -try adjust values).
> Datalist: correct behavior after reset passed collection.

- resources/styles/themes/theme.css
- src/components/toolbar/collections/ToolbarItemsCollection.js
- src/components/toolbar/models/BlinkCheckboxModel.js
- src/components/toolbar/templates/button.html
- src/components/toolbar/views/ActionMenuView.js
- src/components/toolbar/views/ActionView.js
- src/components/toolbar/views/BlinkCheckboxView.js
- src/components/toolbar/views/ButtonView.js
- src/components/toolbar/views/ToolbarCheckboxItemView.js
- src/components/toolbar/views/TriggerButtonView.js
- src/components/toolbar/views/actionMenu/ActionMenuButtonView.js
> Toolbar: update keyboard control.

- demo/public/app/cases/editors/RadioGroupEditor.js
- demo/public/demoPage/views/CanvasView.js
- resources/styles/form.css
- resources/styles/themes/new/index.js
- resources/styles/themes/theme.css
- src/form/editors/RadioGroupEditorView.js
- src/form/editors/impl/radioGroup/templates/radioGroup.hbs
> RadioGroup: readonly layout small fix.

- resources/styles/codemirror.css
- resources/styles/form.css
- resources/styles/list.css
- resources/styles/themes/new/styles.css
- resources/styles/themes/theme.css
> Fix message type values fields styles

- src/form/editors/DatalistEditorView.js
- src/form/editors/impl/datalist/views/InputView.js
- tests/specs/form/DatalistEditorView.spec.js
also fixed not focus input after remove bubble.
> Datalist: if quan === 1 onClear set null to model.

- src/form/editors/DatalistEditorView.js
- src/form/editors/impl/datalist/views/InputView.js
- tests/specs/form/DatalistEditorView.spec.js
> Datalist: fix clear search after panel item click, fix close panel after remove bubble.

- src/layout/popup/PopupView.js
Has no animation on show, unfortunately.
> Popup: add drag.

- demo/public/app/cases/components/Toolbar.js
- resources/styles/common.css
- resources/styles/themes/new/styles.css
- src/components/toolbar/ToolbarView.js
- src/components/toolbar/meta.js
- src/components/toolbar/templates/button.html
- src/components/toolbar/views/ActionMenuView.js
- src/components/toolbar/views/BlinkCheckboxView.js
- src/components/toolbar/views/ButtonView.js
- src/components/toolbar/views/CustomActionGroupView.js
- src/components/toolbar/views/ToolbarCheckboxItemView.js
- src/components/toolbar/views/actionMenu/ActionMenuButtonView.js
- src/views/SearchBarView.js
> Toolbar: add search item, mobile mode.

- resources/styles/themes/new/styles.css
- src/form/editors/DocumentEditorView.js
- src/form/editors/templates/documentEditor.html
- src/list/views/RowView.js
> Fix grid document click.

- resources/styles/dropdown.css
- src/form/editors/DatalistEditorView.js
- src/form/editors/impl/datalist/templates/bubbleItem.hbs
- src/form/editors/impl/datalist/views/BubbleCollectionView.js
- src/form/editors/impl/datalist/views/BubbleItemView.js
> add subtext to dropdown's button

- src/form/editors/DatalistEditorView.ts
- src/form/editors/impl/datalist/views/PanelView.js
> Datalist: add isButtonLimitMode, showSelectedTitle options, add options type.

- src/list/views/selections/SelectionCellView.js
checked/unchecked when  click on cell_selection
> [#454572]fix expand scope event for checkbox

- src/layout/group/GroupView.js
> [#413288]fix open/close of the group within the group
